# Generated by Django 5.2.15 on 2026-07-15 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Match score 50-100 (50=same category, up to +50 for keyword overlap).')),
                ('notified_offer_user', models.BooleanField(default=False)),
                ('notified_request_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='posts.offer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='posts.request')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['offer', '-score'], name='matches_mat_offer_i_93a97e_idx'), models.Index(fields=['request', '-score'], name='matches_mat_request_e8c88d_idx')],
                'unique_together': {('offer', 'request')},
            },
        ),
    ]
