# Generated by Django 5.2.15 on 2026-08-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseofferlink_linked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Optional URL link to the course (e.g. YouTube playlist).', max_length=500),
        ),
    ]
