# Generated by Django 5.2.15 on 2026-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_default_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('tr', 'Turkish')], default='en', help_text='Preferred language for receiving messages on LinguaDuo.', max_length=10),
        ),
    ]
