# Generated by Django 5.2.15 on 2026-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seeker_preferred_format',
            field=models.CharField(choices=[('1_on_1', '1-on-1'), ('group', 'Group'), ('either', 'Either')], default='either', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='seeker_preferred_platform',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('whatsapp_call', 'WhatsApp call'), ('in_app_chat_only', 'In-app chat only'), ('no_preference', 'No preference')], default='no_preference', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='seeker_urgency',
            field=models.CharField(blank=True, choices=[('asap', 'ASAP'), ('within_a_month', 'Within a month'), ('flexible', 'Flexible')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_commitment',
            field=models.CharField(blank=True, choices=[('one_time', 'One-time sessions'), ('ongoing_weekly', 'Ongoing (weekly)'), ('flexible', 'Flexible')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_preferred_platform',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('whatsapp_call', 'WhatsApp call'), ('in_app_chat_only', 'In-app chat only'), ('no_preference', 'No preference')], default='no_preference', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_teaching_format',
            field=models.CharField(choices=[('1_on_1', '1-on-1'), ('group', 'Group'), ('either', 'Either')], default='either', max_length=10),
        ),
    ]
