# Generated by Django 5.2.15 on 2026-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_seeker_preferred_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_fields_completed',
            field=models.BooleanField(default=False),
        ),
    ]
