# Generated by Django 5.2.15 on 2026-08-19 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('platform', 'Platform'), ('course', 'Course'), ('live_section', 'Live Section')], help_text='Type of feedback (platform, course, live_section).', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Object ID of the feedback target (NULL for platform feedback).', null=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_text', models.TextField(help_text='The feedback content.')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this feedback should be publicly visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the feedback target (NULL for platform feedback).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_content_type', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted this feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feedback_type', 'content_type', 'object_id'], name='feedback_fe_feedbac_bce3a1_idx'), models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx'), models.Index(fields=['rating'], name='feedback_fe_rating_c20163_idx'), models.Index(fields=['is_public', 'feedback_type'], name='feedback_fe_is_publ_0ed031_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'feedback_type', 'content_type', 'object_id'), name='unique_feedback_per_user_per_target')],
            },
        ),
        migrations.CreateModel(
            name='RatingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('platform', 'Platform'), ('course', 'Course'), ('live_section', 'Live Section')], help_text='Type of feedback this summary belongs to.', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Object ID of the feedback target (NULL for platform).', null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (1.00 to 5.00).', max_digits=3)),
                ('total_feedbacks', models.PositiveIntegerField(default=0, help_text='Total number of feedbacks.')),
                ('rating_1_count', models.PositiveIntegerField(default=0)),
                ('rating_2_count', models.PositiveIntegerField(default=0)),
                ('rating_3_count', models.PositiveIntegerField(default=0)),
                ('rating_4_count', models.PositiveIntegerField(default=0)),
                ('rating_5_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the feedback target (NULL for platform).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_rating_summaries', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Rating Summary',
                'verbose_name_plural': 'Rating Summaries',
                'ordering': ['feedback_type', 'object_id'],
                'indexes': [models.Index(fields=['feedback_type', 'content_type', 'object_id'], name='feedback_ra_feedbac_c55c9d_idx')],
                'constraints': [models.UniqueConstraint(fields=('feedback_type', 'content_type', 'object_id'), name='unique_rating_summary_per_target')],
            },
        ),
    ]
