# Generated by Django 5.2.15 on 2026-08-20 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(help_text='The reply content.')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this reply should be publicly visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(help_text='The feedback this reply belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback')),
                ('replied_by', models.ForeignKey(blank=True, help_text='User who wrote this reply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Reply',
                'verbose_name_plural': 'Feedback Replies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['feedback', 'created_at'], name='feedback_fe_feedbac_82efce_idx'), models.Index(fields=['replied_by'], name='feedback_fe_replied_6ce87c_idx')],
            },
        ),
    ]
